"""empty message

Revision ID: c2d2896425a4
Revises: 
Create Date: 2019-04-23 16:57:19.696524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d2896425a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('rg', sa.String(length=9), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_editor', sa.Integer(), nullable=True),
    sa.Column('last_edit_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_cpf'), 'person', ['cpf'], unique=True)
    op.create_index(op.f('ix_person_last_edit_time'), 'person', ['last_edit_time'], unique=False)
    op.create_index(op.f('ix_person_timestamp'), 'person', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_timestamp'), table_name='person')
    op.drop_index(op.f('ix_person_last_edit_time'), table_name='person')
    op.drop_index(op.f('ix_person_cpf'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
