"""empty message

Revision ID: ccdfbf9f4a3b
Revises: 
Create Date: 2019-04-25 01:08:34.828957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdfbf9f4a3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_edit_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_editor', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['last_editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_last_edit_time'), 'person', ['last_edit_time'], unique=False)
    op.create_index(op.f('ix_person_timestamp'), 'person', ['timestamp'], unique=False)
    op.create_table('lawsuit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('plaintiff', sa.Integer(), nullable=True),
    sa.Column('defendant', sa.Integer(), nullable=True),
    sa.Column('val', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['defendant'], ['person.id'], ),
    sa.ForeignKeyConstraint(['plaintiff'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawsuit_number'), 'lawsuit', ['number'], unique=True)
    op.create_index(op.f('ix_lawsuit_val'), 'lawsuit', ['val'], unique=False)
    op.create_table('legal_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_person_cnpj'), 'legal_person', ['cnpj'], unique=True)
    op.create_table('natural_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('rg', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_natural_person_cpf'), 'natural_person', ['cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_natural_person_cpf'), table_name='natural_person')
    op.drop_table('natural_person')
    op.drop_index(op.f('ix_legal_person_cnpj'), table_name='legal_person')
    op.drop_table('legal_person')
    op.drop_index(op.f('ix_lawsuit_val'), table_name='lawsuit')
    op.drop_index(op.f('ix_lawsuit_number'), table_name='lawsuit')
    op.drop_table('lawsuit')
    op.drop_index(op.f('ix_person_timestamp'), table_name='person')
    op.drop_index(op.f('ix_person_last_edit_time'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
